name: '🏗️ Build wolfhounds'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/*.json'

jobs:
  build:
    uses: ./.github/workflows/_meta.yaml
    with:
      publish: false
